- name: Initial environment
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - debug:
        msg:
          - "*****************************************************************"
          - "Installing Docker-ce"
          - "*****************************************************************"
    - name:
      wait_for:
        delay: 3
        timeout: 0
    - name: Gather system time
      setup:
        filter: ansible_date_time
    - name: Set start time
      set_fact:
        time_start: "{{ ansible_date_time.epoch }}"
    - debug: var=ansible_date_time.date
    - debug: var=ansible_date_time.time

- name: Install Docker
  hosts: kubeaction
  gather_facts: no
  tags: docker
  roles:
    - { role: docker }

- name: Install HA
  hosts: "{{ hosts | default('kubeaction') }}"
  gather_facts: no
  tags: HA
  roles:
    - { role: common }
    - { role: HA }

- name: Set HA config
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - debug:
        msg:
          - "*****************************************************************"
          - "Setting HA config (include HA-config.yml)"
          - "*****************************************************************"
- include: set-HA-config.yaml


- name: Install kubeaction
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - debug:
        msg:
          - "*****************************************************************"
          - "Install kubeaction(include set-kubeaction.yml)"
          - "*****************************************************************"
- include: set-kubeaction.yaml
