- name: Set HA BACKUP
  hosts: "{{ hosts | default('master[1:2]') }}"
  gather_facts: no
  tags: HA
  roles:
    - { role: common }
  tasks:
    - name: set backup
      lineinfile: dest=/etc/keepalived/keepalived.conf regexp={{ item.regexp }} line={{ item.line}}
      with_items:
        - { regexp: "MASTER", line: "BACKUP"}
        - { regexp: "priority 100", line: "priority 90"}

- name: Set haproxy backend
  hosts: "{{ hosts | default('master') }}"
  gather_facts: no
  tags: HA
  roles:
    - { role: common }
  tasks:
    - name: set haproxy backend
      replace: dest=/etc/haproxy/haproxy.cfg regexp={{ item.a }} replace={{ item.b }}
      with_items:
        - { a: "k8s1 10.16.200.71:6443", b: "{{ hosts.master1.hostname }} {{ hosts.master1.ip }}:6443"}
        - { a: "k8s2 10.16.200.72:6443", b: "{{ hosts.master2.hostname }} {{ hosts.master2.ip }}:6443"}
        - { a: "k8s3 10.16.200.73:6443", b: "{{ hosts.master3.hostname }} {{ hosts.master3.ip }}:6443"}
