apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: {{ groups['master'][0] }}
  bindPort: 6443
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v1.19.9
networking:
  podSubnet: 192.168.0.0/16
controlPlaneEndpoint: {{ groups['vip'][0] }}:6444
dns:
  type: CoreDNS
imageRepository: k8s.gcr.io
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
featureGates:
  SupportIPVSProxyMode: true
mode: ipvs
