- name: prepare kubeaction environment
  yum:
    name: "{{ item }}"
    state: absent
  loop:
    - kubeadm
    - kubectl
    - kubelet

- name: install kubeaction environment
  yum:
    name:
      - kubeadm-1.19.9
      - kubectl-1.19.9
      - kubelet-1.19.9
    state: present


- name: daemon-reload
  raw: systemctl daemon-reload
