- name: prepare kubeaction environment
  yum:
    name: "{{ item }}"
    state: absent
  loop:
    - kubeadm
    - kubectl
    - kubelet

- name: install kubeaction environment
  yum:
    name:
      - kubeadm-1.19.9
      - kubectl-1.19.9
      - kubelet-1.19.9
    state: present


- name: pull kubeaction images
  shell: |
        docker pull registry.cn-hangzhou.aliyuncs.com/google_containers/kube-apiserver:v1.19.9
        docker pull registry.cn-hangzhou.aliyuncs.com/google_containers/kube-controller-manager:v1.19.9
        docker pull registry.cn-hangzhou.aliyuncs.com/google_containers/kube-scheduler:v1.19.9
        docker pull registry.cn-hangzhou.aliyuncs.com/google_containers/kube-proxy:v1.19.9
        docker pull registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.2
        docker pull registry.cn-hangzhou.aliyuncs.com/google_containers/etcd:3.4.13-0
        docker pull registry.cn-hangzhou.aliyuncs.com/google_containers/coredns:1.7.0
  ignore_errors: yes

- name: tag images
  shell: |
        docker tag registry.cn-hangzhou.aliyuncs.com/google_containers/kube-apiserver:v1.19.9 k8s.gcr.io/kube-apiserver:v1.19.9
        docker tag registry.cn-hangzhou.aliyuncs.com/google_containers/kube-controller-manager:v1.19.9 k8s.gcr.io/kube-controller-manager:v1.19.9
        docker tag registry.cn-hangzhou.aliyuncs.com/google_containers/kube-scheduler:v1.19.9 k8s.gcr.io/kube-scheduler:v1.19.9
        docker tag registry.cn-hangzhou.aliyuncs.com/google_containers/kube-proxy:v1.19.9 k8s.gcr.io/kube-proxy:v1.19.9
        docker tag registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.2 k8s.gcr.io/pause:3.2
        docker tag registry.cn-hangzhou.aliyuncs.com/google_containers/etcd:3.4.13-0 k8s.gcr.io/etcd:3.4.13-0
        docker tag registry.cn-hangzhou.aliyuncs.com/google_containers/coredns:1.7.0 k8s.gcr.io/coredns:1.7.0
  ignore_errors: yes

