- name: prepare docker environment
  yum:
    name: "{{ item }}"
    state: absent
  loop:
    - docker-ce
  ignore_errors: yes

- name: install docker-ce
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - docker-ce-20.10.4
    - docker-ce-cli-20.10.4
    - containerd.io
  ignore_errors: yes

- name: make docker dir
  file:
    path: /etc/docker
    state: directory
    mode: 0755

- name: Copy daemon.json to /etc/docker/daemon.json
  become: yes
  template: 
    src: daemon.json
    dest: /etc/docker/daemon.json
    mode: 0644

- name: Start docker
  systemd:
    name: docker.service
    state: started

- name: To prevent docker iptables Forward chain
  lineinfile:
    dest: /usr/lib/systemd/system/docker.service
    insertbefore: "TimeoutSec=0(.*)"
    line: "ExecStartPost=/usr/sbin/iptables -P FORWARD ACCEPT"


- name: Restart the Docker configuration and set the boot up
  systemd:
    name: docker.service
    daemon_reload: yes
    state: restarted
    enabled: yes
